"""raw markdown for questions

Revision ID: cd80fdfb8df6
Revises: 8362f5043c3f
Create Date: 2026-09-16 09:09:52.637842+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd80fdfb8df6'
down_revision: Union[str, Sequence[str], None] = '8362f5043c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('raw_markdown', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'raw_markdown')
    # ### end Alembic commands ###
