"""material figures

Revision ID: f6ec413809e5
Revises: 07d703e0b4c7
Create Date: 2026-09-16 09:44:04.363731+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ec413809e5'
down_revision: Union[str, Sequence[str], None] = '07d703e0b4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_figures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('figure_id', sa.String(length=64), nullable=False),
    sa.Column('src', sa.Text(), nullable=False),
    sa.Column('slice_id', sa.String(length=64), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('keys', sa.JSON(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'figure_id', name='uq_figure_material')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_figures')
    # ### end Alembic commands ###
