"""concepts and concept edges

Revision ID: b5b14e6d16a4
Revises: f6ec413809e5
Create Date: 2026-09-16 12:10:15.046985+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5b14e6d16a4'
down_revision: Union[str, Sequence[str], None] = 'f6ec413809e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('topic_key', sa.String(length=160), nullable=False),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('material_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_key'), 'concepts', ['key'], unique=True)
    op.create_index(op.f('ix_concepts_kind'), 'concepts', ['kind'], unique=False)
    op.create_index(op.f('ix_concepts_status'), 'concepts', ['status'], unique=False)
    op.create_index(op.f('ix_concepts_topic_key'), 'concepts', ['topic_key'], unique=False)
    op.create_table('concept_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_concept_id', sa.Integer(), nullable=False),
    sa.Column('to_concept_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('derived_by', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_concept_id', 'to_concept_id', 'type', name='uq_concept_edge')
    )
    op.create_index(op.f('ix_concept_edges_from_concept_id'), 'concept_edges', ['from_concept_id'], unique=False)
    op.create_index(op.f('ix_concept_edges_to_concept_id'), 'concept_edges', ['to_concept_id'], unique=False)
    op.create_index(op.f('ix_concept_edges_type'), 'concept_edges', ['type'], unique=False)
    op.add_column('knowledge_points', sa.Column('concept_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_knowledge_points_concept_id'), 'knowledge_points', ['concept_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_points', 'concepts', ['concept_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'knowledge_points', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_points_concept_id'), table_name='knowledge_points')
    op.drop_column('knowledge_points', 'concept_id')
    op.drop_index(op.f('ix_concept_edges_type'), table_name='concept_edges')
    op.drop_index(op.f('ix_concept_edges_to_concept_id'), table_name='concept_edges')
    op.drop_index(op.f('ix_concept_edges_from_concept_id'), table_name='concept_edges')
    op.drop_table('concept_edges')
    op.drop_index(op.f('ix_concepts_topic_key'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_status'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_kind'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_key'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###
