"""conversation pinned

给会话加"置顶"（用户自己钉在列表最上面的那些，排序里压过"最近活动"）。

`server_default` 不是可选项：这一列是 NOT NULL，而表里已经有会话 ——
不加默认值，Postgres 没法给存量行填值，整个迁移会直接失败。
（自动生成的那一版就是这样，实测报错。）

Revision ID: f5eecfb7c30c
Revises: cec2ec2de8bb
Create Date: 2026-09-17 12:14:29.989503+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5eecfb7c30c'
down_revision: Union[str, Sequence[str], None] = 'cec2ec2de8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'conversations',
        sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'pinned')
    # ### end Alembic commands ###
