"""question status states and point candidates

Revision ID: 8362f5043c3f
Revises: 9fe6f68ab84e
Create Date: 2026-09-16 09:04:54.566652+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8362f5043c3f'
down_revision: Union[str, Sequence[str], None] = '9fe6f68ab84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('slice_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('thickness', sa.SmallInteger(), nullable=False),
    sa.Column('layers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('terms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'slice_id', 'key', name='uq_candidate')
    )
    op.create_index(op.f('ix_point_candidates_consumed'), 'point_candidates', ['consumed'], unique=False)
    op.create_index(op.f('ix_point_candidates_key'), 'point_candidates', ['key'], unique=False)
    op.create_index(op.f('ix_point_candidates_material_id'), 'point_candidates', ['material_id'], unique=False)
    op.create_index(op.f('ix_point_candidates_slice_id'), 'point_candidates', ['slice_id'], unique=False)
    op.add_column('questions', sa.Column('status', sa.String(length=16), server_default='published', nullable=False))
    op.add_column('questions', sa.Column('layer', sa.String(length=8), server_default='', nullable=False))
    op.add_column('questions', sa.Column('wing', sa.String(length=8), server_default='', nullable=False))
    op.add_column('questions', sa.Column('chapter', sa.String(length=128), server_default='', nullable=False))
    op.add_column('questions', sa.Column('verify_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.create_index(op.f('ix_questions_layer'), 'questions', ['layer'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_index('ix_questions_status_layer', 'questions', ['status', 'layer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_questions_status_layer', table_name='questions')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_layer'), table_name='questions')
    op.drop_column('questions', 'verify_report')
    op.drop_column('questions', 'chapter')
    op.drop_column('questions', 'wing')
    op.drop_column('questions', 'layer')
    op.drop_column('questions', 'status')
    op.drop_index(op.f('ix_point_candidates_slice_id'), table_name='point_candidates')
    op.drop_index(op.f('ix_point_candidates_material_id'), table_name='point_candidates')
    op.drop_index(op.f('ix_point_candidates_key'), table_name='point_candidates')
    op.drop_index(op.f('ix_point_candidates_consumed'), table_name='point_candidates')
    op.drop_table('point_candidates')
    # ### end Alembic commands ###
