"""knowledge space: materials points sources edges question_points

Revision ID: 9fe6f68ab84e
Revises: a1c4e0f27b93
Create Date: 2026-09-16 08:35:44.056494+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fe6f68ab84e'
down_revision: Union[str, Sequence[str], None] = 'a1c4e0f27b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('lines', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_slug'), 'materials', ['slug'], unique=True)
    op.create_index(op.f('ix_materials_subject'), 'materials', ['subject'], unique=False)
    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('thickness', sa.SmallInteger(), nullable=False),
    sa.Column('layers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('producible', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'key', name='uq_point_material_key')
    )
    op.create_index(op.f('ix_knowledge_points_key'), 'knowledge_points', ['key'], unique=False)
    op.create_index(op.f('ix_knowledge_points_material_id'), 'knowledge_points', ['material_id'], unique=False)
    op.create_index('ix_points_kind_layers', 'knowledge_points', ['kind', 'thickness'], unique=False)
    op.create_table('point_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_point_id', sa.Integer(), nullable=False),
    sa.Column('to_point_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('derived_by', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['from_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_point_id', 'to_point_id', 'type', name='uq_edge')
    )
    op.create_index(op.f('ix_point_edges_from_point_id'), 'point_edges', ['from_point_id'], unique=False)
    op.create_index(op.f('ix_point_edges_to_point_id'), 'point_edges', ['to_point_id'], unique=False)
    op.create_index(op.f('ix_point_edges_type'), 'point_edges', ['type'], unique=False)
    op.create_table('point_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('slice_id', sa.String(length=32), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('point_id', 'start_line', 'end_line', name='uq_point_range')
    )
    op.create_index(op.f('ix_point_sources_point_id'), 'point_sources', ['point_id'], unique=False)
    op.create_table('question_points',
    sa.Column('question_id', sa.String(length=96), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'point_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_points')
    op.drop_index(op.f('ix_point_sources_point_id'), table_name='point_sources')
    op.drop_table('point_sources')
    op.drop_index(op.f('ix_point_edges_type'), table_name='point_edges')
    op.drop_index(op.f('ix_point_edges_to_point_id'), table_name='point_edges')
    op.drop_index(op.f('ix_point_edges_from_point_id'), table_name='point_edges')
    op.drop_table('point_edges')
    op.drop_index('ix_points_kind_layers', table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_material_id'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_key'), table_name='knowledge_points')
    op.drop_table('knowledge_points')
    op.drop_index(op.f('ix_materials_subject'), table_name='materials')
    op.drop_index(op.f('ix_materials_slug'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
