"""ai usage daily aggregates

Revision ID: fce2d43e76ba
Revises: 20bd6c290c23
Create Date: 2026-09-15 07:04:28.979053+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce2d43e76ba'
down_revision: Union[str, Sequence[str], None] = '20bd6c290c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_usage', sa.Column('prompt_tokens', sa.Integer(), nullable=False))
    op.add_column('ai_usage', sa.Column('completion_tokens', sa.Integer(), nullable=False))
    op.add_column('ai_usage', sa.Column('last_latency_ms', sa.Integer(), nullable=False))
    op.add_column('ai_usage', sa.Column('last_error', sa.String(length=300), nullable=False))
    op.add_column('ai_usage', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('records', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('records', 'correct',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('records', 'wrong',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('records', 'mastered',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('records', 'flagged',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('records', 'last_at',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('records', 'client_rev',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'client_rev',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('records', 'last_at',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('records', 'flagged',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('records', 'mastered',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('records', 'wrong',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('records', 'correct',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('records', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('ai_usage', 'updated_at')
    op.drop_column('ai_usage', 'last_error')
    op.drop_column('ai_usage', 'last_latency_ms')
    op.drop_column('ai_usage', 'completion_tokens')
    op.drop_column('ai_usage', 'prompt_tokens')
    # ### end Alembic commands ###
